export interface GenStream {
  id: string;
  name: string;
  type: "single" | "grid" | "pip";
  rtspUrl: string;
  sources: string[];
  main: string;
  pip: string;
  corner: "TR" | "TL" | "BR" | "BL";
}

const FF = "exec:ffmpeg -hide_banner -loglevel error";
const ENC = "-map \"[v]\" -c:v libx264 -preset veryfast -tune zerolatency -pix_fmt yuv420p -f rtsp {output}";

function input(url: string): string {
  return `-rtsp_transport tcp -i ${url}`;
}

/** ffmpeg filter for a 2×2 grid (each source scaled to 960×540 → 1920×1080). */
function gridFilter(): string {
  const scales = [0, 1, 2, 3].map((i) => `[${i}:v]scale=960:540,setsar=1[v${i}]`).join(";");
  return `${scales};[v0][v1][v2][v3]xstack=inputs=4:layout=0_0|w0_0|0_h0|w0_h0[v]`;
}

/** ffmpeg filter for picture-in-picture (main 1920×1080, pip 480×270 in a corner). */
function pipFilter(corner: GenStream["corner"]): string {
  const pos: Record<GenStream["corner"], string> = {
    TL: "20:20",
    TR: "main_w-overlay_w-20:20",
    BL: "20:main_h-overlay_h-20",
    BR: "main_w-overlay_w-20:main_h-overlay_h-20",
  };
  return `[0:v]scale=1920:1080,setsar=1[m];[1:v]scale=480:270,setsar=1[p];[m][p]overlay=${pos[corner]}[v]`;
}

function streamValue(s: GenStream): string | null {
  if (s.type === "single") return s.rtspUrl || null;
  if (s.type === "grid") {
    const srcs = s.sources.filter(Boolean);
    if (srcs.length < 4) return null;
    return `${FF} ${srcs.slice(0, 4).map(input).join(" ")} -filter_complex "${gridFilter()}" ${ENC}`;
  }
  // pip
  if (!s.main || !s.pip) return null;
  return `${FF} ${input(s.main)} ${input(s.pip)} -filter_complex "${pipFilter(s.corner)}" ${ENC}`;
}

/** Generate a go2rtc.yml from the configured streams (keyed by stream id). */
export function generateGo2rtcYaml(streams: GenStream[]): string {
  const lines = ["# Generated by Conduit CMS. Composite recipes may need tuning per go2rtc version.", "", "streams:"];
  for (const s of streams) {
    const value = streamValue(s);
    lines.push(`  # ${s.name} (${s.type})`);
    if (value) lines.push(`  ${s.id}: '${value.replace(/'/g, "''")}'`);
    else lines.push(`  # ${s.id}: <incomplete — set its sources in the CMS>`);
  }
  lines.push("");
  return lines.join("\n");
}
